// @ts-nocheck -- gluestack v5-alpha vendored component (regenerated by `gluestack-ui add`)
import { vars } from 'nativewind';

// VM0 token bridge — gluestack 的语义色槽映射到 VM0 值(RGB 三元组,支持 /opacity)。
// 与 theme/theme.ts、src/global.css 同源;改这里 = 改所有 gluestack 组件的皮肤。
export const colors = {
  light: {
    '--primary': '237 78 1', // tint
    '--primary-foreground': '255 255 255', // on-tint
    '--background': '255 255 255', // bg
    '--foreground': '20 23 29', // label
    '--card': '255 255 255', // bg-elevated
    '--card-foreground': '20 23 29',
    '--popover': '255 255 255',
    '--popover-foreground': '20 23 29',
    '--secondary': '243 245 248', // bg-secondary
    '--secondary-foreground': '20 23 29',
    '--muted': '243 245 248', // bg-grouped
    '--muted-foreground': '108 115 128', // ≈ label-secondary(solid)
    '--accent': '237 239 242', // hover fill
    '--accent-foreground': '20 23 29',
    '--destructive': '239 68 68',
    '--success': '42 122 75',
    '--warning': '179 90 0',
    '--border': '197 203 213', // separator
    '--input': '197 203 213',
    '--ring': '237 78 1', // focus = tint
  },
  dark: {
    '--primary': '255 99 33',
    '--primary-foreground': '255 255 255',
    '--background': '12 14 18',
    '--foreground': '243 245 248',
    '--card': '26 30 38',
    '--card-foreground': '243 245 248',
    '--popover': '26 30 38',
    '--popover-foreground': '243 245 248',
    '--secondary': '26 30 38',
    '--secondary-foreground': '243 245 248',
    '--muted': '12 14 18',
    '--muted-foreground': '155 161 173',
    '--accent': '34 38 47', // bg-tertiary
    '--accent-foreground': '243 245 248',
    '--destructive': '255 92 92',
    '--success': '52 179 104',
    '--warning': '232 145 46',
    '--border': '51 57 68',
    '--input': '51 57 68',
    '--ring': '255 99 33',
  },
};

// Config for nativewind vars() - used by provider
export const config = {
  light: vars(colors.light),
  dark: vars(colors.dark),
};
